### ISSUE TITLE
Cannot run KtN in Docker construct

### ISSUE THREAD

**Issue by hycday** [leafac/kill-the-newsletter#107] opened 2024-06-26 16:52 UTC
Hi team,

I am trying to run a version of KtN locally hosted.
However, I am not that familiar with deployment of node, but I feel at ease with Docker.

I think I am also done, but some last part is missing.
Once done I would be glad to provide full instructions for anyone to run it locally using Docker.

So, I have the following Dockerfile file: 
```
FROM node:latest

WORKDIR /app

RUN git clone https://github.com/leafac/kill-the-newsletter.git .
RUN npm install

EXPOSE 8000
EXPOSE 2525

CMD npm start
```

and I have the following docker-compose.yml file:

```
version: "2.1"
services:
  app:
    build: .
    environment:
      EMAIL_DOMAIN: "mydomain.tld"
      ISSUE_REPORT: "mailto:error@mydomain.tld"
      WEB_PORT: 8000
      EMAIL_PORT: 2525
      BASE_URL: "http://sub.mydomain.tld:8000"
      TUNNEL: "sub.mydomain.tld"
    ports:
      - "8000:8000"
      - "2525:2525"
    restart: always
    volumes:
      - "./static/alternate/:/static/alternate/"
      - "./static/feeds/:/static/feeds/"
#everything below is proper to my caddy config
    networks:
      - caddy
    labels:
      caddy: sub.mydomain.tld
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true

```

I did run a ` docker-compose up -d --build` command
I can see that the container is properly running with `docker ps -a`

when I go to http://sub.mydomain.tld:8000 (my domain is different of course) nothing happens, same without the 8000 port.
DNS is properly configured.

When i check the docker logs of the container I see the following error (looping): 

```
Node.js v22.3.0
2024-06-26T16:46:41.106Z        KILL THE NEWSLETTER!    2.0.7   START   email
node:internal/fs/promises:641
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/root/.local/share/caddy/certificates/local/localhost/localhost.key'
    at async open (node:internal/fs/promises:641:25)
    at async Object.readFile (node:internal/fs/promises:1254:14)
    at async file:///app/build/index.mjs:942:10 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.local/share/caddy/certificates/local/localhost/localhost.key'
}

```

and here is where I am lost now...

When I look at your video @leafac here https://youtu.be/507WU47x8HI?t=2666 I see that there is a reference to some js file (which i see here https://github.com/leafac/kill-the-newsletter/tree/main/configuration) 
but I am using caddy to handle the certificates parts...therefore I am not sure how to solve this one (or even if this is actually the issue).

Any help would be welcomed.
I understand that this is Docker and not official per se, but the issue I am having is with deploying the app itself anyway and even if I don't use Docker I believe I would ran to the same issue more or less.

Thanks for any help

Note: I know issue is similar to https://github.com/leafac/kill-the-newsletter/issues/103 but it is not exactly the same, so didn't want to hijack his thread

**Comment by hycday** [comment] 2024-06-26 19:23
so I tried something else, I modified development.mjs, pointing to the crt and key file of my domain, tried to run again, then checked the logs of the docker container and i see this : 

```

2024-06-26T19:13:02.837Z        KILL THE NEWSLETTER!    2.0.7   START   https://[12_char_string]
2024-06-26T19:13:03.717Z        KILL THE NEWSLETTER!    2.0.7   START   backgroundJob   18001
2024-06-26T19:13:03.831Z        KILL THE NEWSLETTER!    2.0.7   START   server  18001
2024-06-26T19:13:03.853Z        SERVER  18001   START
2024-06-26T19:13:03.876Z        KILL THE NEWSLETTER!    2.0.7   START   server  18000
2024-06-26T19:13:03.891Z        SERVER  18000   START
2024-06-26T19:13:03.892Z        KILL THE NEWSLETTER!    2.0.7   START   backgroundJob   18000
2024-06-26T19:13:03.939Z        KILL THE NEWSLETTER!    2.0.7   START   email

```

however, when going to sub.mydomain.tld:8000 I get an `ERR_CONNECTION_REFUSED` error on browser.. and without the port I get a blank page.

**Comment by kooplaah** [comment] 2024-07-10 22:31
I would love to be able to deploy this in my docker setup! I use Traefik to handle my reverse proxy and certs, so ideally I could just remove the config for that part all together, but I'm super unfamiliar with Caddy... 

@hycday I was able to reproduce what you have in your first comment. Couldn't go any further w/o a Caddy setup though.

**Comment by hycday** [comment] 2024-07-10 23:01
@kooplaah without Caddy, it would be : 


```
version: "2.1"
services:
  app:
    build: .
    environment:
      EMAIL_DOMAIN: "mydomain.tld"
      ISSUE_REPORT: "mailto:error@mydomain.tld"
      WEB_PORT: 8000
      EMAIL_PORT: 2525
      BASE_URL: "http://sub.mydomain.tld:8000"
      TUNNEL: "sub.mydomain.tld"
    ports:
      - "8000:8000"
      - "2525:2525"
    restart: always
    volumes:
      - "./static/alternate/:/static/alternate/"
      - "./static/feeds/:/static/feeds/"
```


but note that i dont believe this would work as you need the SSL part, and this you would need to add using your knowledge/setup on Traefik

**Comment by kooplaah** [comment] 2024-07-11 00:02
@hycday I may have just gotten to the same spot as you. I pulled out a bunch of lines in the index.mts file (I commented out any lines referencing the tls cert and key). I do have a bunch of warnings that I haven't looked in to yet, I just got it to build. They may be what's causing some of what I'm seeing. Here's the output of my log file:

`
> start
> nodemon --watch "./package.json" --watch "./tsconfig.json" --watch "./source/" --watch "./static/" --watch "./configuration/" --ext "*" --exec "npm run prepare && node ./build/index.mjs ./configuration/development.mjs"

[nodemon] 3.1.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): package.json tsconfig.json source/**/* static/**/* configuration/**/*
[nodemon] watching extensions: (all)
[nodemon] starting `npm run prepare && node ./build/index.mjs ./configuration/development.mjs`

> prepare
> tsc && build

▲ [WARNING] All "@import" rules must come first [invalid-@import]

    index.css:163:0:
      163 │ @import "@radically-straightforward/javascript/static/index.css";
          ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    index.css:8:0:
      8 │ input[type="text"],
        ╵ ^

▲ [WARNING] All "@import" rules must come first [invalid-@import]

    index.css:164:0:
      164 │ @import "@fontsource-variable/public-sans";
          ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    index.css:8:0:
      8 │ input[type="text"],
        ╵ ^

▲ [WARNING] All "@import" rules must come first [invalid-@import]

    index.css:165:0:
      165 │ @import "bootstrap-icons/font/bootstrap-icons.css";
          ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    index.css:8:0:
      8 │ input[type="text"],
        ╵ ^

2024-07-10T23:58:29.227Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	https://sub.mydomain.tld 	
2024-07-10T23:58:30.607Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18000
2024-07-10T23:58:30.726Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18000
2024-07-10T23:58:30.775Z 	SERVER 	18000 	START
2024-07-10T23:58:30.818Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18003
2024-07-10T23:58:30.860Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18002
2024-07-10T23:58:30.901Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18002
2024-07-10T23:58:30.919Z 	SERVER 	18002 	START
2024-07-10T23:58:30.927Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18001
2024-07-10T23:58:30.928Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18001
2024-07-10T23:58:30.936Z 	SERVER 	18001 	START
2024-07-10T23:58:31.037Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18005
2024-07-10T23:58:31.039Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18006
2024-07-10T23:58:31.049Z 	SERVER 	18005 	START
2024-07-10T23:58:31.058Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18004
2024-07-10T23:58:31.066Z 	SERVER 	18004 	START
2024-07-10T23:58:31.357Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18003
2024-07-10T23:58:31.377Z 	SERVER 	18003 	START
2024-07-10T23:58:31.383Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18007
2024-07-10T23:58:31.394Z 	SERVER 	18007 	START
2024-07-10T23:58:31.455Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	email 	
2024-07-10T23:58:31.564Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	server 	18006
2024-07-10T23:58:31.572Z 	SERVER 	18006 	START
2024-07-10T23:58:31.579Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18005
2024-07-10T23:58:31.624Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18004
2024-07-10T23:58:31.657Z 	KILL THE NEWSLETTER! 	2.0.7 	START 	backgroundJob 	18007
`

**Comment by leafac** [comment] 2024-07-15 20:54
Hi y’all,

Thanks for reaching out.

I recommend that instead of building from source, you [download the binary](https://github.com/leafac/kill-the-newsletter/releases/).

Unfortunately some things changed since that old video of mine. Here are the up-to-date instructions: https://github.com/radically-straightforward/radically-straightforward/blob/main/guides/deployment.md

I don’t recommend that you remove Caddy. It isn’t used only to provision TLS certificates, but also to serve static files, to set security headers, and so forth. If you already have other pieces of infrastructure in place to provision TLS certificates, you may look into configuring Caddy so that it doesn’t try to provision again.

Finally, unfortunately I don’t have the resources to support multiple installation mechanisms, and the preferred way is to use the binary, not Docker. It should still work in Docker, but it’s up to the system administrator to figure it out. So I’m closing this issue for now, but feel free to follow-up if you want.

Best.

**Closed by leafac** 2024-07-15 20:54 UTC
